# Generated by Django 2.2.8 on 2020-03-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='titulo',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
