# Generated by Django 2.2.8 on 2020-03-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20200324_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='fotos',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
