# Generated by Django 2.2.8 on 2020-03-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200324_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id_zonas', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('zona', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lugar',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Zonas'),
        ),
    ]
