# Generated by Django 2.2.8 on 2020-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200328_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='zona',
            field=models.CharField(choices=[('ZS', 'Zona Sur'), ('ZC', 'Zona Centro'), ('ZM', 'Zona Miraflores'), ('ZO', 'Zona Obrajes ')], default='ZA', max_length=100),
        ),
    ]
