# Generated by Django 2.2.8 on 2020-03-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20200328_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zonas',
        ),
    ]
