# Generated by Django 2.2.8 on 2020-03-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_delete_zonas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id_zonas', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('zona', models.CharField(max_length=100)),
            ],
        ),
    ]
