# Generated by Django 2.2.8 on 2020-03-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_zonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Zonas'),
        ),
    ]
